### ISSUE TITLE
Further updates

### ISSUE THREAD

**Issue by LoaderTime** [Arcaea-Infinity/Taikari#3]
Hello.
This issue is asking for the further updates and giving some little suggestions.
I am using 4.4.6 as my reverse enginnering project mainly.
Because this project is not archived yet, and the latest update is on Mar 9, 2022.
So i am wondering if this project is abandoned or it will receive more versions support.

Also, because there are some "Arcaea-server" project on github.
In 3.6.0, the devs increased the ssl secure level (SSL pinning). So its difficult to catch https packets.
I found out some documents about bypassing its ssl pinning (Based on 3.6.3). I tried to use the javascript inside it but it doesnt work very well.
(link if needed:https://cloud.tencent.com/developer/article/2216947)
If possible, please add "remove/bypass SSL pinning" feature. This can be convenient to let players connect to private servers.

**Comment by innocentvoice** [comment]
I believe we shall cease updating this project, which was primarily designed for intercepting SSL packets rather than bypassing SSL pinning or serving other purposes. 

This could be viewed as a conceptual demonstration of engaging with Arcaea API through the game itself. Nevertheless, we appreciate your interest!
